---
kind: pipeline
type: docker
name: test-develop

trigger:
  branch:
    - develop

steps:
  - name: build-test
    image: docker:latest
    commands:
      - docker build -t portfolio-test .
      - echo "✅ Build réussi sur develop"

volumes:
  - name: docker-sock
    path: /var/run/docker.sock

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: deploy-production

trigger:
  branch:
    - main

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: EC2_HOST
      username:
        from_secret: EC2_USER
      key:
        from_secret: EC2_SSH_KEY
      port: 22
      script:
        - cd /home/ubuntu/projects/indtech-site
        - git checkout main
        - git pull origin main
        - docker compose up -d --build portfolio
        - docker image prune -f