server {
    listen 80;
    server_name localhost 13.36.125.230 afridevops.online;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # Support des fichiers statiques
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    
    # Gestion des erreurs
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
}